import Foundation

/// BERT-uncased WordPiece tokenizer matching HuggingFace `tokenizers`'
/// BertNormalizer + BertPreTokenizer + WordPiece exactly, so query token ids
/// equal what transformers.js produced when the index was built. Verified
/// against fixtures generated by ios/scripts/gen-tokenizer-fixtures.mjs.
public struct WordPieceTokenizer: Sendable {
    public let vocab: [String: Int]
    public let clsId: Int
    public let sepId: Int
    public let unkId: Int
    /// words longer than this become [UNK] outright (HF max_input_chars_per_word)
    public let maxInputCharsPerWord = 100
    public let modelMaxLength = 512

    public enum LoadError: Error { case missingVocab, missingSpecialTokens }

    /// Parse a HuggingFace tokenizer.json (only the WordPiece fields are used).
    public init(tokenizerJSON: Data) throws {
        struct File: Codable {
            struct Model: Codable { let vocab: [String: Int] }
            let model: Model
        }
        let file = try JSONDecoder().decode(File.self, from: tokenizerJSON)
        vocab = file.model.vocab
        guard let cls = vocab["[CLS]"], let sep = vocab["[SEP]"], let unk = vocab["[UNK]"] else {
            throw LoadError.missingSpecialTokens
        }
        clsId = cls
        sepId = sep
        unkId = unk
    }

    /// Full encode: [CLS] wordpieces… [SEP], truncated to modelMaxLength.
    public func encode(_ text: String) -> [Int] {
        var ids = [clsId]
        for word in preTokenize(normalize(text)) {
            ids.append(contentsOf: wordPiece(word))
            if ids.count >= modelMaxLength - 1 { break }
        }
        ids = Array(ids.prefix(modelMaxLength - 1))
        ids.append(sepId)
        return ids
    }

    // MARK: - BertNormalizer (clean_text, handle_chinese_chars, lowercase + strip accents)

    func normalize(_ text: String) -> String {
        var cleaned = String.UnicodeScalarView()
        for scalar in text.unicodeScalars {
            if scalar.value == 0 || scalar.value == 0xFFFD || isControl(scalar) { continue }
            if isWhitespace(scalar) {
                cleaned.append(" ")
            } else if isCJK(scalar) {
                cleaned.append(contentsOf: " ".unicodeScalars)
                cleaned.append(scalar)
                cleaned.append(contentsOf: " ".unicodeScalars)
            } else {
                cleaned.append(scalar)
            }
        }
        // lowercase with accent stripping (strip_accents defaults to lowercase)
        let lowered = String(cleaned).lowercased().decomposedStringWithCanonicalMapping
        return String(String.UnicodeScalarView(lowered.unicodeScalars.filter {
            $0.properties.generalCategory != .nonspacingMark
        }))
    }

    // MARK: - BertPreTokenizer (whitespace split, punctuation isolated)

    func preTokenize(_ text: String) -> [String] {
        var words: [String] = []
        var current = ""
        for scalar in text.unicodeScalars {
            if isWhitespace(scalar) {
                if !current.isEmpty { words.append(current); current = "" }
            } else if isPunctuation(scalar) {
                if !current.isEmpty { words.append(current); current = "" }
                words.append(String(scalar))
            } else {
                current.unicodeScalars.append(scalar)
            }
        }
        if !current.isEmpty { words.append(current) }
        return words
    }

    // MARK: - WordPiece greedy longest-match

    func wordPiece(_ word: String) -> [Int] {
        let chars = Array(word)
        guard chars.count <= maxInputCharsPerWord else { return [unkId] }
        var pieces: [Int] = []
        var start = 0
        while start < chars.count {
            var end = chars.count
            var found: Int? = nil
            while start < end {
                let piece = (start > 0 ? "##" : "") + String(chars[start..<end])
                if let id = vocab[piece] { found = id; break }
                end -= 1
            }
            guard let id = found else { return [unkId] }
            pieces.append(id)
            start = end
        }
        return pieces
    }

    // MARK: - character classes (mirror HF tokenizers' definitions)

    private func isWhitespace(_ s: Unicode.Scalar) -> Bool {
        if s == " " || s == "\t" || s == "\n" || s == "\r" { return true }
        return s.properties.generalCategory == .spaceSeparator
    }

    private func isControl(_ s: Unicode.Scalar) -> Bool {
        if s == "\t" || s == "\n" || s == "\r" { return false }
        switch s.properties.generalCategory {
        case .control, .format: return true
        default: return false
        }
    }

    private func isPunctuation(_ s: Unicode.Scalar) -> Bool {
        let v = s.value
        // ASCII blocks: treat all non-alphanumeric ASCII glyphs as punctuation
        if (33...47).contains(v) || (58...64).contains(v) || (91...96).contains(v)
            || (123...126).contains(v) {
            return true
        }
        switch s.properties.generalCategory {
        case .connectorPunctuation, .dashPunctuation, .openPunctuation, .closePunctuation,
            .initialPunctuation, .finalPunctuation, .otherPunctuation:
            return true
        default: return false
        }
    }

    private func isCJK(_ s: Unicode.Scalar) -> Bool {
        switch s.value {
        case 0x4E00...0x9FFF, 0x3400...0x4DBF, 0x20000...0x2A6DF, 0x2A700...0x2B73F,
            0x2B740...0x2B81F, 0x2B820...0x2CEAF, 0xF900...0xFAFF, 0x2F800...0x2FA1F:
            return true
        default: return false
        }
    }
}
